config/routes.rb
Rails.application.routes.draw do

  root to: "tasks#index"

  resources :tasks do
    member do
      post 'start'
      patch 'stop'
      post 'next'
      get 'next'
      get 'start'
      get 'stop'
      get 'track'
      get 'destroy'
    end

    collection do
      get 'track'
    end

    delete 'destroy', on: :member

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
end

app/models/time_track.rb
class TimeTrack < ApplicationRecord
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all.order(created_at: :asc)
    @today_tasks = Task.where("DATE(created_at) = ?", Date.today).order(created_at: :asc)
    #まだcompleteが更新されていないタスク
    @current_task = Task.find_by(complete: 0,start_time: nil)

    @next_task = Task.where("id > ? AND complete = ?", @current_task.id, 0).first if @current_task.present?
    @tasks_by_hour = Task.group("DATE_TRUNC('hour', start_time)").sum("EXTRACT(epoch FROM (end_time - start_time)) / 3600")
  end

  def new
    @task = Task.new
  end

  def start
    @task = Task.find(params[:id])
    @task.update(start_time: Time.current)
    redirect_to track_tasks_path, notice: 'タスクの作業を開始しました。'
  end

  def stop
    @task = Task.find(params[:id])
    @task.update(end_time: Time.current)
    redirect_to track_tasks_path, notice: 'タスクの作業を終了しました。'
  end

  def track
    @today_tasks = Task.where("DATE(created_at) = ?", Date.today)
    @task_data = @today_tasks.map do |task|
      if task.start_time.present? && task.end_time.present?
        [task.name, (task.end_time - task.start_time)]
      else
        [task.name, 0]  # 合計時間をゼロとする
      end
    end
  end

  def next
    @task = Task.find(params[:id])
    @task.update(complete: 1)
    @tasks = Task.all.order(created_at: :asc)
    redirect_to tasks_path, notice: 'タスクを完了しました'
  end


  def create
    task_params = params.require(:task).permit(name: [])
    task_params[:name].each do |name|
      Task.create(name: name)
    end
      redirect_to tasks_path, notice: '登録が完了しました'
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path, notice: 'タスクが更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path, notice: 'タスクが削除されました。'
  end

  private
  def task_params
    params.require(:task).permit(:name, :rest)
  end
end

app/controllers/time_track_controller.rb
class TimeTrackController < ApplicationController
  def new
    @time_track = TimeTrack.new
  end

  def create
    @time_track = TimeTrack.new(time_track_params)
    if @time_track.save
      redirect_to index_path, notice: 'タスクの時間を記録しました'
    else
      render 'new'
    end
  end


  def start
    @task = Task.find(params[:task_id])
    @task_track = @task.task_tracks.build(start_time: Time.current)
    @task_track.save
    redirect_to root_path, notice: 'タスクの作業を開始しました。'
  end

  def stop
    @task = Task.find(params[:task_id])
    @task_track = @task.task_tracks.last
    @task_track.update(end_time: Time.current)
    redirect_to root_path, notice: 'タスクの作業を終了しました。'
  end



  private
  def time_track_params
    params.require(:time_track).permit(:start_time, :end_time, :task_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/time_track_helper.rb
module TimeTrackHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TrackTime
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
  body
    header
      nav
        = link_to 'タスク一覧', root_path, class: "btn btn-light btn-spacing"
        = link_to '新規作成', new_task_path, class: "btn btn-light btn-spacing"
        = link_to '時間計測', track_tasks_path, class: "btn btn-light"
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield

app/views/tasks/_form.html.slim
= form_with(model: @task, local: true) do |form|
  - if @task.errors.any?
    .alert.alert-danger
      h4.alert-heading エラーが発生しました。
      ul
        - @task.errors.full_messages.each do |message|
          li= message

  .form-group
    = form.label :name, 'タスク名'
    = form.text_field :name, class: 'form-control'

  = form.submit '更新', class: 'btn btn-primary'

app/views/tasks/_new.html.slim

= form_with model: Task.new, local: true do |form|
  = form.label :name
  = form.text_field :name
  = form.submit, class: 'btn btn-primary'

app/views/tasks/edit.html.slim
h2 タスクの編集
= render 'form'
= link_to '戻る', root_path, class: 'btn btn-secondary'

app/views/tasks/index.html.slim
h1 TrackTimeToDo

br
br

h2 新規タスク
= link_to '新規作成', new_task_path , class: "btn btn-primary"
br
br

- if @current_task.present?
  table
    tr
      th
        | 現在のタスク ⇨ #{@current_task.name}
      td= link_to '作業を完了する', next_task_path(@current_task), method: :post, class: "btn btn-primary"
      td= link_to '時間を記録する', start_task_path(@current_task), method: :post, class: "btn btn-primary"  unless @current_task.start_time.present?
      td= link_to '記録を終了する', stop_task_path(@current_task), method: :patch, class: "btn btn-primary"  if @current_task.start_time.present?
    tr
      - if @next_task.present?
        td = "Next ⇨ #{@next_task.name}"
      - else
        td = "Next ⇨ 次のタスクはありません。上記のタスクで最後です。"
- else
  table
    tr
      th 現在タスクはありません。追加しましょう。
      th= link_to '新規作成', new_task_path, class: "btn btn-primary"


br
br



h2 今日の全体タスク一覧
.tasks-container
  - @today_tasks.each do |task|
    .task
    br
      = "・#{task.name}"
      span.buttons
        = link_to '編集', edit_task_path(task), class: 'btn btn-warning'
        = link_to '削除', task, method: :delete, class: 'btn btn-danger'

br

h2 作業時間トラッキング
= link_to 'タスクの時間をはかる', track_tasks_path, class: "btn btn-primary"

br
br

app/views/tasks/new.html.slim
h1 新規タスク作成

= form_with model: Task.new, local: true do |form|
  - 4.times do |i|
    = form.text_field "name[]", multiple: true, name: "task[name][]"
    br
  = form.submit nil, class: 'btn btn-primary'

app/views/tasks/track.html.slim
- sum_time = 0
- @today_tasks.each do |task|
  - task_time = task.start_time.present? && task.end_time.present? ? (task.end_time - task.start_time).to_i : 0
  - sum_time += task_time

h2 今日の合計作業時間
- if sum_time < 60
  | #{sum_time} 秒
- else 
  | #{sum_time / 60} 分

= pie_chart @task_data, library: { title: { text: 'Task Distribution' } } 


h2 作業時間トラッキング

- @today_tasks.each do |task|
  = task.name
  br
  - if task.start_time.present?
    | 開始時刻: #{task.start_time.strftime('%H時%M分%S秒')}
    br
  - if task.end_time.present?
    | 終了時刻: #{task.end_time.strftime('%H時%M分%S秒')}
    br/
    - if (task.end_time - task.start_time) < 60
      | 作業時間: #{(task.end_time - task.start_time).to_i} 秒
    - else
      | 作業時間: #{(task.end_time - task.start_time).to_i / 60 } 分
    br
  - else
    = link_to '作業を開始する', start_task_path(task), method: :post, class: "btn btn-primary"  unless task.start_time.present?
    = link_to '終了する', stop_task_path(task), method: :patch, class: "btn btn-warning"  if task.start_time.present?
    br